### ISSUE TITLE
week 11 day 2 Lab

### ISSUE THREAD

**Issue by patrickthesailorman** [ga-wdi-pvd/component-extravaganza#4]
[Stopwatch](https://github.com/patrickthesailorman/react-stopwatch)
[Password validator](https://github.com/patrickthesailorman/react-password-validator)
comfort: 3
complete: 3

**Comment by JosephinaTavera** [comment]
:+1  great job.     For stopwatch, there is a syntax error in the package.json file.    Once I corrected it, the start and stop work great. 
                            Good start with validator, enter some JSX to get it started.
